CREATE PROCEDURE [dbo].[spGenres_Delete]
	@Id INT
AS

BEGIN
	SET NOCOUNT ON;

	DECLARE @ERROR INT
	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
	BEGIN TRANSACTION

	DELETE FROM dbo.[MovieGenres]
	WHERE GenreId = @Id;

	SELECT @ERROR = @@ERROR
	IF (@ERROR <> 0) BEGIN
		ROLLBACK TRANSACTION
	END

	DELETE
	FROM dbo.[Genres]
	WHERE Id = @Id

	SELECT @ERROR = @@ERROR
	IF (@ERROR <> 0) BEGIN
		ROLLBACK TRANSACTION
	END ELSE BEGIN
		COMMIT TRANSACTION
	END
END