CREATE PROCEDURE [dbo].[spMovies_Delete]
	@Id INT
AS

BEGIN
	SET NOCOUNT ON;

	DECLARE @ERROR INT
	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
	BEGIN TRANSACTION

	DELETE FROM dbo.[MovieActors]
	WHERE MovieId = @Id;

	SELECT @ERROR = @@ERROR
	IF (@ERROR <> 0) BEGIN
		ROLLBACK TRANSACTION
	END

	DELETE FROM dbo.[MovieGenres]
	WHERE MovieId = @Id;

	SELECT @ERROR = @@ERROR
	IF (@ERROR <> 0) BEGIN
		ROLLBACK TRANSACTION
	END

	DELETE FROM dbo.[MovieRatings]
	WHERE MovieId = @Id;

	SELECT @ERROR = @@ERROR
	IF (@ERROR <> 0) BEGIN
		ROLLBACK TRANSACTION
	END

	DELETE FROM dbo.[Movies]
	WHERE Id = @Id;

	SELECT @ERROR = @@ERROR
	IF (@ERROR <> 0) BEGIN
		ROLLBACK TRANSACTION
	END ELSE BEGIN
		COMMIT TRANSACTION
	END
END